name: ${plugin_name}
author: ${plugin_author}
version: ${plugin_version}
website: ${plugin_website}

description: ${plugin_description}

main: net.benwoodworth.fastcraft.implementations.bukkit.BukkitFastCraft
